# Generated by Django 3.0.3 on 2020-04-02 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('cardno', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('cardmoney', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('cardtime', models.DateField()),
                ('carpassword', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'db_table': 'card',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Classinfo',
            fields=[
                ('cid', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'classinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Collegeinfo',
            fields=[
                ('cid', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'collegeinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Costinfo',
            fields=[
                ('cnumber', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('ctime', models.DateField()),
                ('ccost', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'db_table': 'costinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fillinfo',
            fields=[
                ('rnumber', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('rtime', models.DateField()),
                ('rmoney', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'db_table': 'fillinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Majorinfo',
            fields=[
                ('mid', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('mname', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'majorinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Studentinfo',
            fields=[
                ('sno', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=8)),
                ('ssex', models.CharField(blank=True, max_length=4, null=True)),
                ('sage', models.DateField()),
            ],
            options={
                'db_table': 'studentinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Losinfo',
            fields=[
                ('cardno', models.ForeignKey(db_column='cardno', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='child.Card')),
                ('ltime', models.DateField()),
            ],
            options={
                'db_table': 'losinfo',
                'managed': False,
            },
        ),
    ]
